/***
 * 地图瓦片枚举
 */
export const TILE_TYPE_ENUM = {
  WALL_ROW_START: "ROW_WALL_START",
  WALL_ROW_CENTER: "WALL_ROW_CENTER",
  WALL_ROW_END: "ROW_WALL_END",
  WALL_COLUMN_START: "COLUMN_WALL_START",
  WALL_COLUMN_CENTER: "WALL_COLUMN_CENTER",
  WALL_COLUMN_END: "COLUMN_WALL_END",
  CLIFF_ROW_START: 'CLIFF_ROW_START',
  CLIFF_ROW_CENTER: 'CLIFF_ROW_CENTER',
  CLIFF_ROW_END: 'CLIFF_ROW_END',
  FLOOR: "FLOOR",
}

/***
 * 活动单位枚举
 */
export const ENEMY_TYPE_ENUM = {
  SKELETON_WOODEN: 'SKELETON_WOODEN',
  SKELETON_IRON: 'SKELETON_IRON',
  SPIKES_ONE: 'SPIKES_ONE',
  SPIKES_TWO: 'SPIKES_TWO',
  SPIKES_THREE: 'SPIKES_THREE',
  SPIKES_FOUR: 'SPIKES_FOUR',
	BURST_FLOOR: 'BURST_FLOOR',
	DOOR_ROW: "DOOR_ROW",
	DOOR_COLUMN: "DOOR_COLUMN",
}

/***
 * 角色方向枚举
 */
export const DIRECTION_ENUM = {
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  TOP: 'TOP',
  BOTTOM: 'BOTTOM',
}

/***
 * 控制按钮枚举
 */
export const CONTROLLER_ENUM = {
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  TOP: 'TOP',
  BOTTOM: 'BOTTOM',
  TURNLEFT: 'TURNLEFT',
  TURNRIGHT: 'TURNRIGHT'
}

/***
 * 角色状态枚举
 */
export const PLAYER_STATE = {
  IDLE: 'IDLE',
  ATTACK: 'ATTACK',
  TURNLEFT: 'TURNLEFT',
  TURNRIGHT: 'TURNRIGHT',
	BLOCK:'BLOCK',
	DEATH:'DEATH',
}

/***
 * 事件类型枚举
 */
export const EVENT_ENUM = {
	PLAYER_CTRL: 'PLAYER_CTRL',
	PLAYER_MOVE:'PLAYER_MOVE',
	ATTACK_ENEMY:'ATTACK_ENEMY',
	ATTACK_PLAYER:'ATTACK_PLAYER',
	NEXT_LEVEL: 'NEXT_LEVEL',
	RECORD_STEP:'RECORD_STEP',
	REVOKE_STEP: 'REVOKE_STEP',
	SCREEN_SHAKE: 'SCREEN_SHAKE',
	RESTART_LEVEL: 'RESTART_LEVEL',
	GAME_OVER: 'GAME_OVER',
}

/***
 * 有限状态机参数枚举
 */
export const FSM_PARAM_TYPE_ENUM = {
	NUMBER: 'NUMBER',
	BOOLEAN: 'BOOLEAN',
	TRIGGER: 'TRIGGER',
}
